### PR TITLE
Create new attribute: servicePortName

### PR DESCRIPTION
**Pull request by piyushpgupta**
Create new attribute: servicePortName to custom name to the serviceport name

### CODE REVIEW

**Comment by mflendrich** [comment]
Hi @piyushpgupta,

1. This change needs to go to the [charts repo](https://github.com/Kong/charts) - when releasing kong-operator, the chart gets embedded from there verbatim. We don't make changes to the chart in this repo.
2. Why do you need this?

Closing this PR because (1) means that this PR needs to be created in another repo, as stated above. But please help us understand the motivation first. Thanks!

**Comment by piyushpgupta** [comment]
@mflendrich thanks for update , I will create PR in charts repository . Motivation is to allow user to configure service port name .
It give more flexibility in choosing service port name .

We also have validation webhook which allow , service with port name .

**Comment by mflendrich** [comment]
Could you please elaborate on _why_ changing the service port name here is necessary?

**Comment by piyushpgupta** [comment]
@mflendrich  do you mean changing in the particular file or why change in port name is required? 
Chaging is port name is required to get through the validation webhook that we have which allow services port name with particular format like protocol-suffix 
With kong operator no options is allowed to provide port name , it's blocks our adoption for kong operator .
We are using kong for our production operations.
Currently we are evaluating operator

**Pull request closed without merging**
