### PR TITLE
update kong chart to v1.4.1 for kong operator.

### PR DESCRIPTION
**Pull request by morvencao**
resolve: https://github.com/Kong/kong-operator/issues/4

### CODE REVIEW

**Comment by morvencao** [comment]
Plase @hbagdi take a look.
I have tested it in my local env, it is working.

/cc @gyliu513

**Comment by hbagdi** [comment]
We will get back as soon as we can. Thank you for the PR and testing this. Appreciate it!

**Comment by rainest** [comment]
I'd thought that the ability to use a repository discussed in https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md#use-an-existing-chart would allow it to track updates remotely, but it looks like that's just pulling it down locally from the repo when initializing :(

Chart 1.5.0 should be out soon, so waiting on that to place another commit updating the chart files on top before merging. Rest of changes look fine.

**Comment by morvencao** [comment]
@rainest Thanks for update.

**Comment by hbagdi** [comment]
Please fill in the contributor form to claim your Kong swag: https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#contributor-t-shirt

**Pull request closed without merging**
